### ISSUE TITLE
Causing MATLAB shuts down

### ISSUE THREAD

**Issue by cloudy-sfu** [dgleich/matlab-bgl#23]
The most simplified script to make this problem reappear:
```
x = zeros(2);
x = sparse(x);
c = clustering_coefficients(x);
```
It doesn't raise an error, instead, MATLAB shuts down.

**Comment by dgleich** [comment]
Does this work on a non-empty graph? If so, just add a line to clustering coefficients to return 0 for the empty graph.

**Comment by cloudy-sfu** [comment]
Yes, It works on a non-empty matrix. However, it’s weird that it shuts down, instead of raising an error. Why doesn’t it raise an error?
Thank you for answering, and I'm curious about it.

**Comment by dgleich** [comment]
I had thought we had good empty checks in all the codes, but this one must
have gotten missed...

Sorry about that, the easiest thing to do is just to add a check that the
graph has any edges. I'm surprised this actually throws an error as it
seems like the algorithm ought to work in such cases. I wonder if Mathworks
changed howo they store these things.

Sorry again!

**Comment by cloudy-sfu** [comment]
The suggestion to fix this issue: https://github.com/dgleich/matlab-bgl/pull/24
