### ISSUE TITLE
Unrecognized function or variable 'planar_test_mex'.

### ISSUE THREAD

**Issue by yushangdi** [dgleich/matlab-bgl#26]
Hello,

I installed the matlabBGL package from Matlab add-ons, but I cannot use the planarity testing algorithm. I got:

```
Unrecognized function or variable 'planar_test_mex'.

Error in boyer_myrvold_planarity_test (line 41)
    is_planar = planar_test_mex(A,0);
```

I am using Mac with MATLAB R2021a. Does anyone know why this happens? Thanks!

**Comment by yushangdi** [comment]
I tried to download a pre-compiled version from here: https://dgleich.wordpress.com/2010/07/08/matlabbgl-osx-64-bit/

but then I got the following problem:

Invalid MEX-file '/Users/sy/Library/Application Support/MathWorks/MATLAB Add-Ons/Collections/MatlabBGL/matlab_bgl/private/planar_test_mex.mexmaci64':
dlopen(/Users/sy/Library/Application Support/MathWorks/MATLAB Add-Ons/Collections/MatlabBGL/matlab_bgl/private/planar_test_mex.mexmaci64, 6): Library not
loaded: @loader_path/libmex.dylib
  Referenced from: /Users/sy/Library/Application Support/MathWorks/MATLAB Add-Ons/Collections/MatlabBGL/matlab_bgl/private/planar_test_mex.mexmaci64
  Reason: image not found

Error in boyer_myrvold_planarity_test (line 41)
    is_planar = planar_test_mex(A,0);

**Comment by yushangdi** [comment]
I finally got it solved here! https://answers.launchpad.net/matlab-bgl/+question/69161

**Comment by dgleich** [comment]
Thanks, I pushed an edit to the readme to point out this link!
