### ISSUE TITLE
compilation issues of libmbgl with boost 1.47 and gcc 4.6.2 in archlinux

### ISSUE THREAD

**Issue by luoq** [dgleich/matlab-bgl#8]
1. some things changed in boost. 
   a. boost/property_map.hpp no longer exsits. Change to boost/property_map/property_map.hpp seems work.
   b. boost/graph/edmunds_karp_max_flow.hpp is deprecated,boost/graph/edmonds_karp_max_flow.hpp should be used.Function edmunds_karp_max_flow is changed to edmonds_karp_max_flow.Maybe function names in libmbgl should also use edmonds instead of edmunds.
2. A const version of reverse_edge_pmap_helper::operator[] in max_flow.cc is needed or compilation fails.
3. shortest_paths.cc and layouts.cc can not  be compiled.I cannot tell the reasons.

**Comment by dgleich** [comment]
I'll take a look soon.  Thanks for sending the info and the pull request.

**Comment by luoq** [comment]
See the error log of compiling shortest_paths.cc in http://pastebin.com/F2aFfDyL

**Comment by dgleich** [comment]
It looks like there is something wrong with the weight vector derived from the csr array, I'll have to take a look.  It'll be a little bit.  Do you need this soon? 

David

**Comment by luoq** [comment]
I'm using version 4.0 with precompiled mex files currently.So it's not urgent.

**Comment by luoq** [comment]
See the error log of compiling layouts.cc http://pastebin.com/71fZ7k15

**Comment by dgleich** [comment]
I'm starting to work on this one, will let you know when it's finished.

**Comment by dgleich** [comment]
Okay, I've got it compiling on osx and ubuntu 10.10 (gcc-4.4) with Boost 1.48.  Can you check if the v5 branch will compile on your platform now too?

**Comment by luoq** [comment]
libmbgl compiles well with boost 1.47 and gcc 4.6.2 in archlinux(32bit).And in my new 64bit laptop with gentoo ,boost 1.46.1 and gcc 4.5.3,it works too.But some minor problem in max_flow_mex.c needs to be fixed so that compile.m works.See my pull request.Maybe you want to clean the edmo(u)ds in the documents and matlab function option name.

**Comment by dgleich** [comment]
Fixed.  Sorry about those.  I hadn't gotten around to testing things in Matlab yet.
